background="#ffffff"
text="#000000"
subtle="#000000"
warning-text="#d7005f"
text-special-one="#000000"
text-special-two="#d7005f"
top-bar-background="#4271ae"
top-bar-text="#ffffff"
status-bar-background="#f0f0f0"
status-bar-text="#000000"
status-bar-view-background="#505050"
status-bar-view-text="#ffffff"
list-selected-background="#4271ae"
list-selected-text="#ffffff"
command-text="#000000"
list-selected-inactive-background="#6d6d6d"
list-selected-inactive-text="#ffffff"
controls-text="#000000"
controls-highlight="#f92672"
autocomplete-background="#fafafa"
autocomplete-text="#000000"
autocomplete-selected-background="#4271ae"
autocomplete-selected-text="#ffffff"
button-color-one="#4271ae"
button-color-two="#fafafa"
timeline-name-background="#f0f0f0"
timeline-name-text="#000000"
